[project]
name = "trec-tot-2025"
version = "0.1.1"
authors = [{ name = "Anthony Miyaguchi", email = "acmiyaguchi@gatech.edu" }, {name = "Wenxin Zhou", email = "wenxinmmb@gmail.com" }, { name = "Ritesh Mehta", email = "rmehta307@gatech.edu" }]
description = "DS@GT TREC 2025 Tip-of-the-Tongue Track"
readme = "README.md"
requires-python = ">=3.8"
dynamic = ["dependencies"]

[project.urls]
Homepage = "https://github.com/dsgt-kaggle-clef/trec-tot-2025"
Issues = "https://github.com/dsgt-kaggle-clef/trec-tot-2025/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = { file = "requirements.txt" }

[tool.setuptools.packages.find]
where = ["."]
include = ["my_task_package*"]
namespaces = false
