#!/usr/bin/env python3
"""
Script to create the query_generation.ipynb notebook from JSON content
"""

import json

# The notebook JSON content
notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Query Generation Notebook\n",
    "\n",
    "This notebook implements a query generation pipeline following these steps:\n",
    "1. Choose a topic from the 24 topic categories\n",
    "2. Load the relevant CSV file with topic-specific documents\n",
    "3. Select top-K documents by confidence score\n",
    "4. Pick a random target document and get relevant documents\n",
    "5. Search for documents in parquet shards to get full content\n",
    "6. Generate embeddings using BGE-M3 model\n",
    "7. Create FAISS index and find similar documents\n",
    "8. Extract keywords and compute similarities\n",
    "9. Generate query using LLM with keyword clues"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 1: Imports and Setup\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import random\n",
    "import os\n",
    "from pathlib import Path\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# For embeddings\n",
    "from sentence_transformers import SentenceTransformer\n",
    "import torch\n",
    "\n",
    "# For FAISS\n",
    "import faiss\n",
    "\n",
    "# For keyword extraction\n",
    "from keybert import KeyBERT\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "\n",
    "# For LLM\n",
    "from transformers import AutoTokenizer, AutoModelForCausalLM\n",
    "import torch\n",
    "\n",
    "print(\"All imports completed successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 2: Configuration and Constants\n",
    "\n",
    "# Topic selection (from the 24 categories)\n",
    "TOPIC = \"entertainment\"  # You can change this to any of the 24 topics\n",
    "\n",
    "# File paths\n",
    "TOPIC_CSV_PATH = f\"/workspace/topic_grouped_csv/{TOPIC}.csv\"\n",
    "PARQUET_SHARDS_DIR = \"/workspace/split_parquet_shards/\"\n",
    "\n",
    "# Parameters\n",
    "TOP_K = 100  # Number of top documents to consider\n",
    "FAISS_TOP_K = 10  # Number of similar documents to retrieve from FAISS\n",
    "KEYWORD_TOP_K = 20  # Number of keywords to extract\n",
    "\n",
    "# Model configurations\n",
    "EMBEDDING_MODEL = \"BAAI/bge-m3\"  # Can be changed to other models\n",
    "KEYWORD_MODEL = \"all-MiniLM-L6-v2\"  # For KeyBERT\n",
    "LLM_MODEL = \"google/gemma-2b-it\"  # Can be changed to other models\n",
    "\n",
    "print(f\"Configuration:\")\n",
    "print(f\"Topic: {TOPIC}\")\n",
    "print(f\"Top-K: {TOP_K}\")\n",
    "print(f\"Embedding Model: {EMBEDDING_MODEL}\")\n",
    "print(f\"LLM Model: {LLM_MODEL}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 3: Load Topic-Specific CSV and Select Top-K Documents\n",
    "\n",
    "def load_topic_csv(csv_path, top_k=100):\n",
    "    \"\"\"Load topic-specific CSV and return top-K documents by confidence.\"\"\"\n",
    "    print(f\"Loading CSV from: {csv_path}\")\n",
    "    \n",
    "    # Load the CSV file\n",
    "    df = pd.read_csv(csv_path)\n",
    "    print(f\"Loaded {len(df)} documents from {TOPIC} topic\")\n",
    "    print(f\"Columns: {df.columns.tolist()}\")\n",
    "    \n",
    "    # Sort by confidence score and get top-K\n",
    "    df_sorted = df.sort_values('confidence', ascending=False).head(top_k)\n",
    "    print(f\"Selected top {len(df_sorted)} documents by confidence\")\n",
    "    print(f\"Confidence range: {df_sorted['confidence'].min():.4f} - {df_sorted['confidence'].max():.4f}\")\n",
    "    \n",
    "    return df_sorted\n",
    "\n",
    "# Load the topic CSV\n",
    "topic_df = load_topic_csv(TOPIC_CSV_PATH, TOP_K)\n",
    "print(\"\\nSample of top documents:\")\n",
    "print(topic_df.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 4: Select Target Document and Relevant Documents\n",
    "\n",
    "def select_target_and_relevant_docs(df, target_idx=None):\n",
    "    \"\"\"Select a random target document and return relevant documents.\"\"\"\n",
    "    if target_idx is None:\n",
    "        target_idx = random.randint(0, len(df) - 1)\n",
    "    \n",
    "    target_doc = df.iloc[target_idx]\n",
    "    relevant_docs = df.drop(target_idx).copy()\n",
    "    \n",
    "    print(f\"Selected target document at index {target_idx}:\")\n",
    "    print(f\"  ID: {target_doc['id']}\")\n",
    "    print(f\"  Title: {target_doc['title']}\")\n",
    "    print(f\"  Confidence: {target_doc['confidence']:.4f}\")\n",
    "    print(f\"\\nRelevant documents count: {len(relevant_docs)}\")\n",
    "    \n",
    "    return target_doc, relevant_docs\n",
    "\n",
    "# Select target and relevant documents\n",
    "target_doc, relevant_docs = select_target_and_relevant_docs(topic_df)\n",
    "target_id = target_doc['id']\n",
    "relevant_ids = relevant_docs['id'].tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 5: Search for Documents in Parquet Shards\n",
    "\n",
    "def find_document_in_shards(doc_id, shards_dir):\n",
    "    \"\"\"Search for a document ID across all parquet shards.\"\"\"\n",
    "    shard_files = [f for f in os.listdir(shards_dir) if f.endswith('.parquet')]\n",
    "    shard_files.sort()\n",
    "    \n",
    "    for shard_file in shard_files:\n",
    "        shard_path = os.path.join(shards_dir, shard_file)\n",
    "        try:\n",
    "            df = pd.read_parquet(shard_path)\n",
    "            if doc_id in df['id'].values:\n",
    "                doc = df[df['id'] == doc_id].iloc[0]\n",
    "                print(f\"Found document {doc_id} in {shard_file}\")\n",
    "                return doc\n",
    "        except Exception as e:\n",
    "            print(f\"Error reading {shard_file}: {e}\")\n",
    "            continue\n",
    "    \n",
    "    print(f\"Document {doc_id} not found in any shard\")\n",
    "    return None\n",
    "\n",
    "def get_documents_content(doc_ids, shards_dir):\n",
    "    \"\"\"Get full content for multiple document IDs.\"\"\"\n",
    "    documents = {}\n",
    "    \n",
    "    for doc_id in doc_ids:\n",
    "        doc = find_document_in_shards(doc_id, shards_dir)\n",
    "        if doc is not None:\n",
    "            documents[doc_id] = {\n",
    "                'id': doc['id'],\n",
    "                'title': doc['title'],\n",
    "                'text': doc['text'],\n",
    "                'url': doc['url']\n",
    "            }\n",
    "    \n",
    "    return documents\n",
    "\n",
    "# Get target document content\n",
    "print(\"Searching for target document...\")\n",
    "target_content = find_document_in_shards(target_id, PARQUET_SHARDS_DIR)\n",
    "\n",
    "if target_content is not None:\n",
    "    print(f\"\\nTarget document content:\")\n",
    "    print(f\"Title: {target_content['title']}\")\n",
    "    print(f\"Text preview: {target_content['text'][:200]}...\")\n",
    "else:\n",
    "    print(\"Target document not found!\")\n",
    "    exit()\n",
    "\n",
    "# Get relevant documents content\n",
    "print(f\"\\nSearching for {len(relevant_ids)} relevant documents...\")\n",
    "relevant_docs_content = get_documents_content(relevant_ids, PARQUET_SHARDS_DIR)\n",
    "print(f\"Found {len(relevant_docs_content)} relevant documents\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 6: Generate Embeddings\n",
    "\n",
    "def load_embedding_model(model_name):\n",
    "    \"\"\"Load the embedding model.\"\"\"\n",
    "    print(f\"Loading embedding model: {model_name}\")\n",
    "    model = SentenceTransformer(model_name)\n",
    "    print(f\"Model loaded successfully!\")\n",
    "    return model\n",
    "\n",
    "def generate_embeddings(texts, model):\n",
    "    \"\"\"Generate embeddings for a list of texts.\"\"\"\n",
    "    print(f\"Generating embeddings for {len(texts)} texts...\")\n",
    "    embeddings = model.encode(texts, show_progress_bar=True)\n",
    "    print(f\"Generated embeddings shape: {embeddings.shape}\")\n",
    "    return embeddings\n",
    "\n",
    "# Load embedding model\n",
    "embedding_model = load_embedding_model(EMBEDDING_MODEL)\n",
    "\n",
    "# Prepare texts for embedding\n",
    "target_text = target_content['text']\n",
    "relevant_texts = [doc['text'] for doc in relevant_docs_content.values()]\n",
    "\n",
    "# Generate embeddings\n",
    "target_embedding = generate_embeddings([target_text], embedding_model)[0]\n",
    "relevant_embeddings = generate_embeddings(relevant_texts, embedding_model)\n",
    "\n",
    "print(f\"\\nTarget embedding shape: {target_embedding.shape}\")\n",
    "print(f\"Relevant embeddings shape: {relevant_embeddings.shape}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 7: Create FAISS Index and Find Similar Documents\n",
    "\n",
    "def create_faiss_index(embeddings, dimension):\n",
    "    \"\"\"Create a FAISS index for the embeddings.\"\"\"\n",
    "    print(f\"Creating FAISS index with dimension {dimension}...\")\n",
    "    \n",
    "    # Normalize embeddings for cosine similarity\n",
    "    faiss.normalize_L2(embeddings)\n",
    "    \n",
    "    # Create index\n",
    "    index = faiss.IndexFlatIP(dimension)  # Inner product for cosine similarity\n",
    "    index.add(embeddings.astype('float32'))\n",
    "    \n",
    "    print(f\"FAISS index created with {index.ntotal} vectors\")\n",
    "    return index\n",
    "\n",
    "def search_similar_documents(query_embedding, index, relevant_docs, top_k=10):\n",
    "    \"\"\"Search for similar documents using FAISS.\"\"\"\n",
    "    print(f\"Searching for top-{top_k} similar documents...\")\n",
    "    \n",
    "    # Normalize query embedding\n",
    "    query_embedding_norm = query_embedding.copy()\n",
    "    faiss.normalize_L2(query_embedding_norm.reshape(1, -1))\n",
    "    \n",
    "    # Search\n",
    "    scores, indices = index.search(query_embedding_norm.astype('float32'), top_k)\n",
    "    \n",
    "    # Get the relevant document IDs\n",
    "    relevant_ids = list(relevant_docs_content.keys())\n",
    "    \n",
    "    similar_docs = []\n",
    "    for i, (score, idx) in enumerate(zip(scores[0], indices[0])):\n",
    "        if idx < len(relevant_ids):\n",
    "            doc_id = relevant_ids[idx]\n",
    "            doc_info = relevant_docs_content[doc_id]\n",
    "            similar_docs.append({\n",
    "                'rank': i + 1,\n",
    "                'doc_id': doc_id,\n",
    "                'title': doc_info['title'],\n",
    "                'score': float(score),\n",
    "                'text': doc_info['text']\n",
    "            })\n",
    "    \n",
    "    return similar_docs\n",
    "\n",
    "# Create FAISS index\n",
    "embedding_dim = relevant_embeddings.shape[1]\n",
    "faiss_index = create_faiss_index(relevant_embeddings, embedding_dim)\n",
    "\n",
    "# Search for similar documents\n",
    "similar_docs = search_similar_documents(target_embedding, faiss_index, relevant_docs_content, FAISS_TOP_K)\n",
    "\n",
    "print(f\"\\nTop {FAISS_TOP_K} similar documents:\")\n",
    "for doc in similar_docs:\n",
    "    print(f\"{doc['rank']}. {doc['title']} (Score: {doc['score']:.4f})\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 8: Extract Keywords and Compute Similarities\n",
    "\n",
    "def load_keyword_model(model_name):\n",
    "    \"\"\"Load the keyword extraction model.\"\"\"\n",
    "    print(f\"Loading keyword model: {model_name}\")\n",
    "    model = KeyBERT(model_name)\n",
    "    print(f\"Keyword model loaded successfully!\")\n",
    "    return model\n",
    "\n",
    "def extract_keywords(text, model, top_k=20):\n",
    "    \"\"\"Extract keywords from text using KeyBERT.\"\"\"\n",
    "    try:\n",
    "        keywords = model.extract_keywords(text, keyphrase_ngram_range=(1, 2), \n",
    "                                         stop_words='english', \n",
    "                                         use_maxsum=True, \n",
    "                                         nr_candidates=top_k*2, \n",
    "                                         top_k=top_k)\n",
    "        return [kw for kw, score in keywords]\n",
    "    except Exception as e:\n",
    "        print(f\"Error extracting keywords: {e}\")\n",
    "        return []\n",
    "\n",
    "def compute_keyword_similarity(target_keywords, relevant_keywords_list):\n",
    "    \"\"\"Compute similarity between target keywords and relevant documents keywords.\"\"\"\n",
    "    # Combine all relevant keywords\n",
    "    all_relevant_keywords = set()\n",
    "    for keywords in relevant_keywords_list:\n",
    "        all_relevant_keywords.update(keywords)\n",
    "    \n",
    "    # Find unique terms from target that are not in relevant\n",
    "    target_keywords_set = set(target_keywords)\n",
    "    unique_terms = target_keywords_set - all_relevant_keywords\n",
    "    \n",
    "    # If no unique terms, use top target keywords\n",
    "    if not unique_terms:\n",
    "        unique_terms = set(target_keywords[:10])\n",
    "    \n",
    "    return list(unique_terms)\n",
    "\n",
    "# Load keyword model\n",
    "keyword_model = load_keyword_model(KEYWORD_MODEL)\n",
    "\n",
    "# Extract keywords from target document\n",
    "print(\"Extracting keywords from target document...\")\n",
    "target_keywords = extract_keywords(target_content['text'], keyword_model, KEYWORD_TOP_K)\n",
    "print(f\"Target keywords: {target_keywords}\")\n",
    "\n",
    "# Extract keywords from similar documents\n",
    "print(f\"\\nExtracting keywords from {len(similar_docs)} similar documents...\")\n",
    "similar_docs_keywords = []\n",
    "for doc in similar_docs:\n",
    "    keywords = extract_keywords(doc['text'], keyword_model, KEYWORD_TOP_K)\n",
    "    similar_docs_keywords.append(keywords)\n",
    "    print(f\"Document {doc['rank']}: {keywords[:5]}...\")\n",
    "\n",
    "# Compute unique terms\n",
    "unique_terms = compute_keyword_similarity(target_keywords, similar_docs_keywords)\n",
    "print(f\"\\nUnique terms from target: {unique_terms}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 9: Load LLM and Generate Query\n",
    "\n",
    "def load_llm_model(model_name):\n",
    "    \"\"\"Load the LLM model for query generation.\"\"\"\n",
    "    print(f\"Loading LLM model: {model_name}\")\n",
    "    \n",
    "    try:\n",
    "        tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
    "        model = AutoModelForCausalLM.from_pretrained(\n",
    "            model_name,\n",
    "            torch_dtype=torch.float16,\n",
    "            device_map=\"auto\",\n",
    "            trust_remote_code=True\n",
    "        )\n",
    "        print(f\"LLM model loaded successfully!\")\n",
    "        return tokenizer, model\n",
    "    except Exception as e:\n",
    "        print(f\"Error loading LLM model: {e}\")\n",
    "        return None, None\n",
    "\n",
    "def create_query_prompt(unique_terms, topic):\n",
    "    \"\"\"Create a prompt template for query generation.\"\"\"\n",
    "    prompt = f\"\"\"You are a search query generator. Given a set of keywords from a document in the {topic} topic, generate a natural language search query that would help find this document.\n",
    "\n",
    "Keywords: {', '.join(unique_terms)}\n",
    "\n",
    "Generate a search query that captures the main topic and key concepts:\n",
    "\"\"\"\n",
    "    return prompt\n",
    "\n",
    "def generate_query_with_llm(prompt, tokenizer, model, max_length=100):\n",
    "    \"\"\"Generate a query using the LLM.\"\"\"\n",
    "    try:\n",
    "        inputs = tokenizer(prompt, return_tensors=\"pt\").to(model.device)\n",
    "        \n",
    "        with torch.no_grad():\n",
    "            outputs = model.generate(\n",
    "                **inputs,\n",
    "                max_new_tokens=max_length,\n",
    "                temperature=0.7,\n",
    "                do_sample=True,\n",
    "                pad_token_id=tokenizer.eos_token_id\n",
    "            )\n",
    "        \n",
    "        generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)\n",
    "        # Extract only the generated part (after the prompt)\n",
    "        query = generated_text[len(prompt):].strip()\n",
    "        \n",
    "        return query\n",
    "    except Exception as e:\n",
    "        print(f\"Error generating query: {e}\")\n",
    "        return None\n",
    "\n",
    "# Load LLM model\n",
    "tokenizer, llm_model = load_llm_model(LLM_MODEL)\n",
    "\n",
    "if tokenizer is not None and llm_model is not None:\n",
    "    # Create prompt\n",
    "    prompt = create_query_prompt(unique_terms, TOPIC)\n",
    "    print(f\"\\nGenerated prompt:\")\n",
    "    print(prompt)\n",
    "    \n",
    "    # Generate query\n",
    "    print(f\"\\nGenerating query with LLM...\")\n",
    "    generated_query = generate_query_with_llm(prompt, tokenizer, llm_model)\n",
    "    \n",
    "    if generated_query:\n",
    "        print(f\"\\nGenerated Query: {generated_query}\")\n",
    "        print(f\"\\nTarget Document Title: {target_content['title']}\")\n",
    "    else:\n",
    "        print(\"Failed to generate query\")\n",
    "else:\n",
    "    print(\"LLM model not available, skipping query generation\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 10: Summary and Results\n",
    "\n",
    "print(\"=\" * 80)\n",
    "print(\"QUERY GENERATION PIPELINE SUMMARY\")\n",
    "print(\"=\" * 80)\n",
    "\n",
    "print(f\"\\nTopic: {TOPIC}\")\n",
    "print(f\"Target Document ID: {target_id}\")\n",
    "print(f\"Target Document Title: {target_content['title']}\")\n",
    "print(f\"Target Document URL: {target_content['url']}\")\n",
    "\n",
    "print(f\"\\nTop {FAISS_TOP_K} Similar Documents:\")\n",
    "for doc in similar_docs:\n",
    "    print(f\"  {doc['rank']}. {doc['title']} (Score: {doc['score']:.4f})\")\n",
    "\n",
    "print(f\"\\nTarget Keywords: {target_keywords}\")\n",
    "print(f\"Unique Terms: {unique_terms}\")\n",
    "\n",
    "if 'generated_query' in locals() and generated_query:\n",
    "    print(f\"\\nGenerated Query: {generated_query}\")\n",
    "\n",
    "print(\"\\n\" + \"=\" * 80)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

def create_notebook():
    """Create the query_generation.ipynb notebook"""
    with open('query_generation.ipynb', 'w') as f:
        json.dump(notebook_content, f, indent=1)
    print("✅ Successfully created query_generation.ipynb")

if __name__ == "__main__":
    create_notebook() 